/*
 * DO NOT EDIT!
 * 
 * Automatically generated source code by Pitch Developer Studio
 * Licensed to LP Internal Development 2020
 *
 * Copyright (C) 2006-2020 Pitch Technologies AB. All rights reserved.
 * Use is subject to license terms.
 */

/**
 * Main package for the API generated by Pitch Developer Studio.
 * <p>
 * Start by creating an instance of the {@link devstudio.generatedcode.HlaWorld} interface by calling
 * {@link devstudio.generatedcode.HlaWorld.Factory#create HlaWorld.Factory.create()}.
 */
package devstudio.generatedcode;
