* graphs
3. request satisfaction delay as a function of BLOCK_SIZE
> decide how long delay is acceptable.

* ideer för prestanda
byt grafsökningsalgoritm beroende på grafens struktur
* vidare arbete
** hitta bästa vägen
kräver att vi har någon funktion som jämför två vägar och avgör hur attributerna ska jämföras.

det kräver även att vi inte längre behöver ha den kortaste vägen.


* howto
** How to create, add, run and use a FOM
1. start VisualOMT and devleop the FOM, save the module.

2.   Open Pitch Dev Studio.
2.1: Add the .xml file under interaction/object classes
2.2: click "Java Code Generate" and load it into a directory "MyFederate"

3:   Open idea (IntelliJ)
3.1: load the directory HLA_code.
3.2: go to File->Project Structure->Modules
3.3: click the '+' to the far right and select JARs or dirs and add the following:
- /home/lukas/Desktop/exjobb/[module name]/lib/rti_driver.jar
- /opt/Pitch/prti1516e/lib/prti1516e.jar
- /opt/JDKit/jdk.13.0.2 (may already be there)

3.4 kryssa ned ruta, i den inbyggda filutforskaren högerklicka src->New->Java Class
3.5 write code, right click the PathFinder().simulate() call in the main method to run.

4. Open pitchrti1516e.

(5. how to use pitch recorder)
* todo
** TODO (varje radio ska bara lyssna bara på de requests som den skickar)
** TODO bitBucket.
** TODO uppdatera bara nw max var 5:e sek?

** ideer
Om vi har två grafer G1 = (V, E1) och G2 = (V, E2) och E2 tillhör E1, så behöver vi inte räkna ut om det finns en väg genom G2 mellan två noder n1 och n2 om vi vet att den finns i G1. Det kan fortfarande finnas anledning att ta reda på om det finns en kortare väg genom G2 mellan nod n1 och n2. 

Man kan cachea lösningar, den totala minnesanvändningen blir lägre, man kan föra statistik över vilka vägar som många noder tar och på så sätt "föreslå" till en nod var den bör gå för att öka uppkopplingen i nätverket.

** report
*** distinguera mellan multihop-simulator och federationens simulering.
*** lägg till abstrakt och slutsats

* pass
yPitch%123
lukas123

** Mattermost
username: lukas.pohlman
password: yPitch%123

* qs
Hur används .vomt filer efter att jag sparat ett projekt i VisualOMT? I Dev studio importeras ju endast .xml filer?

skickar jag med hela arrayen nu?

om man inte ska göra någon ny FOM modul så behöver man inte besöka visualOMT, utan man kan bara importera rätt XML filer i Dev Studio. Hur vet man vilka XML filer man ska importera? I ConnSimulation2 så ligger det fler XML filer än vad jag kan minnas att vi importerade.

Vad gör man i Object/Interaction Classes i Dev. Studio?  
