* graphs
3. request satisfaction delay as a function of BLOCK_SIZE
> decide how long delay is acceptable.

* ideer för prestanda
byt grafsökningsalgoritm beroende på grafens struktur
* vidare arbete
** hitta bästa vägen
kräver att vi har någon funktion som jämför två vägar och avgör hur attributerna ska jämföras.

* howto
** How to create, add, run and use a FOM
1. start VisualOMT and devleop the FOM, save the module.

2.   Open Pitch Dev Studio.
2.1: Add the .xml file under interaction/object classes
2.2: click "Java Code Generate" and load it into a directory "HLA_code"

3:   Open idea (IntelliJ)
3.1: load the directory HLA_code.
3.2: go to File->Project Structure->Modules
3.3: click the '+' to the far right and select JARs or dirs and add the following:
- /home/lukas/Desktop/multihop-routing/[module name]/lib/rti_driver.jar
- /opt/Pitch/prti1516e/lib/prti1516e.jar
- /opt/JDKit/jdk.13.0.2 (may already be there)

3.4 kryssa ned ruta, i den inbyggda filutforskaren högerklicka src->New->Java Class
3.5 write code, right click the PathFinder().simulate() call in the main method to run.

4. Open pitchrti1516e.

(5. how to use pitch recorder)
* sparad LaTeX kod
** ist för UML:
\begin{enumerate}
    \item Main.java \\
        Innehåller ett huvudprogram. Programmet startas och ser till att grafen uppdateras så fort en ny inmatning kommer in från RTI:n. Används av Graph.java för att bygga upp grafen med hjälp av grannmatriser, och av DynamicQueue.java för att schemalägga förfrågningar.
    \item Graph.java \\
        Bygger upp grafen och utför en grafsökningarna. 
    \item Radio.java \\
        I denna klass är det definierat för varje typ av kommunikation vad som krävs av förbindelserna för att kommunikationen ska kunna föras över nätverket. Används av Graph.java för att bygga upp rätt graf för en viss typ av kommunikation.
    \item DynamicQueue.java \\
        Schemalägger förfrågningar. Används av Graph.java för att hämta förfrågningarna.
\end{enumerate}{}

* todo
** TODO passa kö och nätverk som referens till MultihopSimulator.java
alltså inte en kopia. när Main.java uppdaterar dem så ska Mul.Simulator.java ha den nyaste versionen av dem.
** TODO tråda lösning
** TODO se till att federaterna kan startas när som helst.
sätt timer på bruteforce så att den bara bygger om var 10:e sek lr ngt.
** TODO Implementera req. respnse
** DONE DynamicQueue bör ej bygga på en volatile LinkedList
implementera med någon typ av trådsäker variant ist.
** TODO transactionID i FOM:en
** TODO bitBucket.

* pass
yPitch%123
lukas123

** Mattermost
username: lukas.pohlman
password: yPitch%123

* qs
Hur används .vomt filer efter att jag sparat ett projekt i VisualOMT? I Dev studio importeras ju endast .xml filer?

skickar jag med hela arrayen nu?

om man inte ska göra någon ny FOM modul så behöver man inte besöka visualOMT, utan man kan bara importera rätt XML filer i Dev Studio. Hur vet man vilka XML filer man ska importera? I ConnSimulation2 så ligger det fler XML filer än vad jag kan minnas att vi importerade.

Vad gör man i Object/Interaction Classes i Dev. Studio?  
