* howto
** How to create, add, run and use a FOM
1. start VisualOMT and devleop the FOM, save the module.

2.   Open Pitch Dev Studio.
2.1: Add the .xml file under interaction/object classes
2.2: click "Java Code Generate" and load it into a directory "MyFederate"

3:   Open idea (IntelliJ)
3.1: load the directory HLA_code.
3.2: go to File->Project Structure->Modules
3.3: click the '+' to the far right and select JARs or dirs and add the following:
- /home/lukas/Desktop/exjobb/[module name]/lib/rti_driver.jar
- /opt/Pitch/prti1516e/lib/prti1516e.jar
- /opt/JDKit/jdk.13.0.2 (may already be there)

3.4 kryssa ned ruta, i den inbyggda filutforskaren högerklicka src->New->Java Class
3.5 write code, right click the PathFinder().simulate() call in the main method to run.

4. Open pitchrti1516e.

(5. how to use pitch recorder)
* todo
** presentation
*** TODO bildtexter
*** TODO tydligare inledning
*** TODO dela upp Federat-delen och koddelen
*** TODO bildtexter
** implementation
*** TODO Gör Radio till en extends Node
*** TODO uppdatera FOMarna, så att multihop inte har en send request

** other
*** TODO bitBucket 
* pass
yPitch%123
lukas123

** Mattermost
username: lukas.pohlman
password: yPitch%123


* PRES
- same presentation
- HLA will be skipped
- figures, if you have a question

i think the title of the thesis encapsulates what the work is about, so let me explain what the title means


C:
there can be different communication types in this network. A might want to send its position to C, and thats one communication type. Or it might want to have voice communication with C, and thats another communication type. Different communication types may require different things of the connections.

This is a network containing all connections between all pairs of nodes. From this network we can extract one graph per communication type containing only the edges that can be traveersed by that communication type. 



- each graph only contains the edges that can be traversed by that communicationtype

I'll be presenting my thesis, which i named simulation for 
