/*
 * DO NOT EDIT!
 * 
 * Automatically generated source code by Pitch Developer Studio
 * Licensed to LP Internal Development 2020
 *
 * Copyright (C) 2006-2020 Pitch Technologies AB. All rights reserved.
 * Use is subject to license terms.
 */

/**
 * Package with all the exceptions for the API generated by Pitch Developer Studio.
 */
package devstudio.generatedcode.exceptions;
